#!/usr/bin/perl

# dorpm
# John Jacobsen, NPX Designs, Inc., jacobsen\@npxdesigns.com
# Started: Tue Jul 12 23:00:28 2005

# Procedure:
# update release notes
# tag project with desired <tag>
# "make rpm" invokes dorpm <tag>

use strict;

my $project = "domhub-tools";

print "Welcome to $0.\n";

die "Sorry bud, gotta be root to do this.\n" unless $< == 0;

my $version = shift; chomp $version;
sub usage;
die usage unless defined $version;
print "Version is $version.\n";
my $rpmver = $version; 
$rpmver =~ s/^V//; 
$rpmver =~ s/rel\-//;
$rpmver =~ s/\-/\./g;
my $verproj = "$project"."-$rpmver";
my $reldir = "rel-100";
print "RPM version is $rpmver.\n";

chdir "../.." or die "Can't CD ../.. : $!\n";

my $r;
$r = `rm -rf $verproj 2>&1`; die "$r\n" unless $r eq "";
$r = `cp -Rp $project $verproj 2>&1`; die "$r\n" unless $r eq "";
$r = `tar czf /tmp/$verproj.tgz --exclude=$verproj/CVS $verproj 2>&1`;
die "$r\n" unless $r eq "";
$r = `cp /tmp/$verproj.tgz /usr/src/redhat/SOURCES 2>&1`; die "$r\n" unless $r eq "";
$r = `cp $verproj/$reldir/$project.spec /usr/src/redhat/SPECS/$verproj.spec 2>&1`; 
die "$r\n" unless $r eq "";
chdir "/usr/src/redhat" or die "Can't CD to /usr/src/redhat: $!\n";
system "rpmbuild -ba -D 'VER $rpmver' -D 'REL 0' SPECS/$verproj.spec 2>&1";
print $r;
$r = `rm -rf $verproj 2>&1`; die "$r\n" unless $r eq "";

exit;

sub usage { 
    return <<EOF;
Usage: $0 <version>
EOF
;
}
__END__

